//
// Created by abbas on 7/16/2024.
//

#ifndef CONSOLIDATED_PROJECT_NUMBERGUESSINGGAME_H
#define CONSOLIDATED_PROJECT_NUMBERGUESSINGGAME_H

void NumberGuessingGame();
#endif //CONSOLIDATED_PROJECT_NUMBERGUESSINGGAME_H
